# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7322356de96528ae2c1056ff32b455d0e4e6660f3bc15e9322ab40fe082da74891bb501c97b1a347b0547fdfe487a987f5afdbbb57db3f08ff75694efe7c19d9

test:
  secret_key_base: 14c5f5ed2f579bf6e768e16d36d941ee946497bb46c576d7ac306c09be5f01e1ba0725004168f5fc86398173772a6effc0f52a704c36fa03bc11dfb6306b3bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
